Create Table INTERVIEW_DB.PLAYGROUND_SAHIRAM.Conditions_per_million
AS
(Select _ROW, NEW_CASES_PER_MILLION, NEW_DEATHS_PER_MILLION, TOTAL_DEATHS_PER_MILLION, TOTAL_CASES_PER_MILLION,POPULATION, LOCATION,COUNTRY,CONTINENT,DATE
from INTERVIEW_DB.PLAYGROUND_SAHIRAM.COVID_19_INDONESIA_SAHIRAM)