Create Table INTERVIEW_DB.PLAYGROUND_SAHIRAM.Daily_updates
AS
(Select _ROW, NEW_RECOVERED, NEW_DEATHS, NEW_ACTIVE_CASES, NEW_CASES,LOCATION,COUNTRY,CONTINENT,DATE
from INTERVIEW_DB.PLAYGROUND_SAHIRAM.COVID_19_INDONESIA_SAHIRAM)