Create Table INTERVIEW_DB.PLAYGROUND_SAHIRAM.Total_cases_till_now
AS
(Select _ROW, TOTAL_ACTIVE_CASES, TOTAL_RECOVERED, TOTAL_DEATHS, TOTAL_CASES,LOCATION,COUNTRY,CONTINENT,DATE
from INTERVIEW_DB.PLAYGROUND_SAHIRAM.COVID_19_INDONESIA_SAHIRAM)